"use strict";

const fs = require("node:fs");
const path = require("node:path");
const Ajv = require("ajv");
const standalone = require("ajv/dist/standalone").default;

// UTF-16 bounds intentionally match desktop/Kotlin String.length. No dynamic
// compilation or Ajv runtime dependency is shipped to Electron or the Worker.
const ajv = new Ajv({ code: { source: true }, unicode: false, logger: false, strict: true });
const names = { eventSummary: "event-summary", eventDetail: "event-detail", decisionIntent: "decision-intent" };
const exportsMap = {};
for (const [name, file] of Object.entries(names)) {
  const schema = require(path.join("..", "schemas", file + ".json"));
  ajv.addSchema(schema);
  exportsMap[name] = schema.$id;
}
const output = "// Generated by npm run build:protocol; do not edit.\n" + standalone(ajv, exportsMap) + "\n";
if (/require\(/.test(output)) throw new Error("Protocol validators must have no runtime dependencies");
const target = path.join(__dirname, "..", "generated", "validators.js");
if (process.argv.includes("--check")) {
  if (fs.readFileSync(target, "utf8").replace(/\r\n/g, "\n") !== output) throw new Error("Protocol validators are stale");
} else {
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, output);
}
